//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace grupoesparza.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin_user_table
    {
        public admin_user_table()
        {
            this.pedido_agradecimiento = new HashSet<pedido_agradecimiento>();
            this.pedido_panoramica = new HashSet<pedido_panoramica>();
        }
    
        public long id_user { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public long id_universidad { get; set; }
        public long id_grupo { get; set; }
        public long id_carrera { get; set; }
        public int Telefono { get; set; }
        public int estatus_account { get; set; }
        public int estatus_active { get; set; }
        public System.DateTime fecha_registro { get; set; }
    
        public virtual universidades universidades { get; set; }
        public virtual grupos grupos { get; set; }
        public virtual carreras carreras { get; set; }
        public virtual ICollection<pedido_agradecimiento> pedido_agradecimiento { get; set; }
        public virtual ICollection<pedido_panoramica> pedido_panoramica { get; set; }
    }
}
