//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace grupoesparza.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class esparza_dbEntities : DbContext
    {
        public esparza_dbEntities()
            : base("name=esparza_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<admin_auth_table> admin_auth_table { get; set; }
        public DbSet<admin_user_table> admin_user_table { get; set; }
        public DbSet<bases> bases { get; set; }
        public DbSet<carreras> carreras { get; set; }
        public DbSet<galerias> galerias { get; set; }
        public DbSet<grupos> grupos { get; set; }
        public DbSet<maderas> maderas { get; set; }
        public DbSet<paquetes> paquetes { get; set; }
        public DbSet<pedido_agradecimiento> pedido_agradecimiento { get; set; }
        public DbSet<pedido_panoramica> pedido_panoramica { get; set; }
        public DbSet<placa_escultura> placa_escultura { get; set; }
        public DbSet<textos> textos { get; set; }
        public DbSet<tonos> tonos { get; set; }
        public DbSet<universidades> universidades { get; set; }
    }
}
