//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace grupoesparza.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class grupos
    {
        public grupos()
        {
            this.admin_user_table = new HashSet<admin_user_table>();
        }
    
        public long id_grupo { get; set; }
        public long id_carrera { get; set; }
        public string grado { get; set; }
        public string grupo { get; set; }
        public int num_contratos { get; set; }
        public int estatus { get; set; }
    
        public virtual ICollection<admin_user_table> admin_user_table { get; set; }
        public virtual carreras carreras { get; set; }
    }
}
