//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace grupoesparza.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class paquetes
    {
        public paquetes()
        {
            this.bases = new HashSet<bases>();
        }
    
        public long id_paquete { get; set; }
        public string NombrePaquete { get; set; }
        public int estatus { get; set; }
    
        public virtual ICollection<bases> bases { get; set; }
    }
}
