//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace grupoesparza.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedido_panoramica
    {
        public long id_pedido { get; set; }
        public long id_user { get; set; }
        public long id_base { get; set; }
        public long id_madera { get; set; }
        public long id_tono { get; set; }
        public long id_placa { get; set; }
        public int TipoBase { get; set; }
        public string Comentarios { get; set; }
        public int Biselado { get; set; }
        public System.DateTime Fecha_Alta { get; set; }
        public int estatus { get; set; }
    
        public virtual admin_user_table admin_user_table { get; set; }
        public virtual bases bases { get; set; }
        public virtual maderas maderas { get; set; }
        public virtual tonos tonos { get; set; }
        public virtual placa_escultura placa_escultura { get; set; }
    }
}
