//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace grupoesparza.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class slider
    {
        public int id { get; set; }
        public string image { get; set; }
        public string titulo { get; set; }
        public string texto { get; set; }
        public int presentar { get; set; }
        public Nullable<int> isHyperLink { get; set; }
        public string LinkURL { get; set; }
    }
}
