//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace grupoesparza.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class textos
    {
        public textos()
        {
            this.pedido_agradecimiento = new HashSet<pedido_agradecimiento>();
        }
    
        public long id_texto { get; set; }
        public string Texto { get; set; }
        public int tipo { get; set; }
        public int estatus { get; set; }
    
        public virtual ICollection<pedido_agradecimiento> pedido_agradecimiento { get; set; }
    }
}
